server:
  port: 6000
spring:
  application:
    name: AIGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///aigou_product?useUnicode=true&characterEncoding=utf8
    password: 123456
    username: root
