server:
  port: 2000
spring:
  application:
    name: AIGOU-zuul
zuul:
  routes:
    plat:
      path: /plat/**
      serviceId: AIGOU-plat
    product:
      path: /product/**
      serviceId: AIGOU-product
  ignored-services: '*'
  prefix: /services